# Generated by Django 3.1.4 on 2021-06-12 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_photos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='photos',
        ),
    ]
