# Generated by Django 3.1.4 on 2021-07-23 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_delete_photos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('TeaLights', 'TeaLights'), ('Lamps', 'Lamps'), ('Penstand', 'Penstand'), ('Planterbottle', 'Planterbottle'), ('Plantertestube', 'Plantertestube')], default='', max_length=50),
        ),
    ]
