# Generated by Django 3.1.4 on 2021-07-28 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20210723_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Tea Lights', 'Tea Lights'), ('Lamps', 'Lamps'), ('Pen Stand', 'Pen Stand'), ('Planter Bottle', 'Planter Bottle'), ('Planter Testube', 'Planter Testube')], default='', max_length=50),
        ),
    ]
