runtime: python38 # or another supported version


instance_class: F2

entrypoint: gunicorn -b :$PORT EnSite.wsgi

env_variables:
  # GAE_APPLICATION: True
  BUCKET_NAME: "enactus-300513.appspot.com"
  SECRET_KEY: "kjlsdkhdfakojtjsnKKSKALSnUB!GwfaYffsUgfdvd^784tef#()lmgldm|lmslrfghxddgs"
  GOOGLE_APPLICATION_CREDENTIALS: "enactus.json"
  DJANGO_SETTINGS_MODULE: "EnSite.settings.prod"
  STATIC_URL: 'https://storage.googleapis.com/enactus-300513.appspot.com/'

handlers:
# Matches requests to /images/... to files in static/images/...
- url: /static
  static_dir: static

# - url: /images
#   static_dir: static/images

- url: /.*
  # secure: always
  # redirect_http_response_code: 301
  script: auto