# Generated by Django 3.1.2 on 2020-11-08 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_blog_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image1',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image2',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
